package exceptionHandling;

public class Test {
    public static void main(String[] args) {

        int a[]= { 12,10,20,14};
        int b[]= {2,5,0,7};

        for (int i = 0; i <a.length ; i++) {

         try{   System.out.println(divide(a[i],b[i]));

        }
      catch (Exception e ){
          System.out.println(e.getMessage());
      }}
        System.out.println(" good job ");

    }

    static int  divide(int a,int  b){
        return a/b;
    }
}






2. package exceptionHandling;

import Stu.Student;

public class Test2 {
    public static void main(String[] args) {

        int a[]= { 12,10,20,14};
        int b[]= {2,5,0,7};

        for (int i = 0; i <a.length ; i++) {

            try{   System.out.println(divide(a[i],b[i]));

            }
            catch (Exception e ){
                System.out.println(e.getMessage());
            }}
        System.out.println(" good job ");



    }

    static int divide(int a,int  b) {

        try {
            return a / b;
        } catch (Throwable e) {
            System.out.println(e);
         return -1;
        }
    }
}


package exceptionHandling;
/* 1️⃣ Basic Try-Catch

Write a program that takes two integers as input and performs division.
Handle division by zero using a try-catch block.

 */
import java.util.Scanner;
public class Practice1 {
    public static void main(String[] args) {
        Scanner sc = new Scanner (System.in);

        System.out.println("enter divident ");
        int divident = sc.nextInt();

        int divisor;
        while (true){
            System.out.println("enter divisor ");
            divisor= sc.nextInt();

            if(divisor!= 0) {
                break;
            }
            System.out.println("divisor cant be non zero , Please enter a non zero number ");

        }


        divide(divident,divisor);
        sc.close();

    }

    public static void divide(int a,int b){

       try{
           System.out.println("answer is " + a/b);
       }
       catch (ArithmeticException e ){
           System.out.println(e.getMessage());
       }
    }


}


package exceptionHandling;
import java.util.Scanner;
public class Pratice2 {
    public static void main(String[] args) {
Scanner sc = new Scanner(System.in);
        System.out.println("enter size of array ");
        int size = sc.nextInt();

        int arr[]= new int[size];

        System.out.println("enter elements of the array ");

       try{
           for (int i = 0; i <=size ; i++) {
               arr[i]= sc.nextInt();

           }}
       catch (ArrayIndexOutOfBoundsException e){
           System.out.println(e);
       }
        System.out.println("elements are");

        for (int i = 0; i <size ; i++) {
            System.out.print(arr[i]+ " ");

        }
        sc.close();
    }
}

package exceptionHandling;
import java.util.Scanner;
public class Pratice2 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("enter size of array ");
        int size = sc.nextInt();

        int arr[]= new int[size];

        System.out.println("enter elements of the array ");

        try{
            for (int i = 0; i <=size ; i++) {
                arr[i]= sc.nextInt();

            }}
        catch (ArrayIndexOutOfBoundsException e){
            System.out.println(e);
        }
        System.out.println("elements are");

        for (int i = 0; i <size ; i++) {
            System.out.print(arr[i]+ " ");

        }
        sc.close();
    }
}
